import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { Video } from 'cloudinary-react';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Optimized Video</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <p className={styles.description}>Cloudinary Optimized Video</p>
        <div className={styles.grid}>
          <Video
            cloudName={process.env.NEXT_PUBLIC_CLOUD_NAME}
            publicId='video'
            controls='true'
            className={styles.video}
          />
        </div>
      </main>
    </div>
  );
}